import type { Metadata } from "next";

import { Sidebar } from "@/components/layout";

export const metadata: Metadata = {
  title: "Fundación Vincent Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-screen h-screen flex">
      <Sidebar />

      <div className="w-full h-screen overflow-x-hidden overflow-y-auto">
        { children }
      </div>
    </main>
  );
}
